{% set name = "dagit" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a2409a89d3226bd6873ec294b1098590b37826ef3cb076104520ee35f08c4eb7

build:
  number: 0
  noarch: python
  entry_points:
    - dagit-cli = dagit.cli:main
    - dagit = dagit.dagit:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - click >=7.0
    - dagster {{ version }}.*
    - dagster_graphql {{ version }}.*
    - enum-compat >=0.0.1
    - flask >=0.12.4
    - flask-cors >=3.0.6
    - flask-graphql >=2.0.0
    - flask-sockets >=0.2.1
    - future
    - gevent
    - gevent-websocket >=0.10.1
    - graphql-core >=2.1,<3
    - graphql-ws >=0.3.0
    - nbconvert >=5.4.0
    - pyyaml >=3.10,<5
    - watchdog >=0.8.3

test:
  imports:
    - dagit
    - dagit.schema
    - dagit.templates
  requires:
    - pip
  commands:
    - pip check
    - dagit-cli --help
    - dagit --help

about:
  home: "https://github.com/dagster-io/dagster"
  license: Apache-2.0
  license_family: APACHE
  license_file:  LICENSE
  summary: "Web UI for dagster."

extra:
  recipe-maintainers:
    - conda-forge/dagster
